'''
Dataloader for rollout datasets generated by UniVLA (Emu-based VLA).

Data is produced by:
  UniVLA/reference/RoboVLMs/eval/libero/evaluate_libero_emu.py

Directory layout expected under `cfg.dataset.data_path`:
  env_records/
      <task_id>_ep<ep_idx>_succ<0|1>.pkl   – episode-level metadata
      <task_id>_ep<ep_idx>_succ<0|1>.mp4   – replay video
  policy_records/
      <NNNNNN>_meta.pkl                     – one file per inference step

Policy record keys
------------------
  hidden_states : np.ndarray  (N_tok, 4096), float32
      Last-layer hidden states for every generated action token.
  probs         : np.ndarray  (N_tok,), float32
      Chosen-token probability for each action token.
  top_k_probs   : np.ndarray  (N_tok, K), float32
      Top-K probabilities for each action token.
  actions       : np.ndarray  (pred_horizon, action_dim), float32
      Predicted action chunk.

Env record keys (subset used here)
------------------------------------
  model_infer_times, replan_steps, task_suite_name, task_id,
  task_description, episode_idx, episode_success
'''

from collections import defaultdict
import glob
import pickle
from pathlib import Path
from typing import Union

import natsort
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

from failure_prob.conf import Config
from failure_prob.utils.failure_metrics import compute_stac_metrics_single
from .utils import Rollout, set_task_min_step, split_rollouts_by_seen_unseen, process_tensor_idx_rel
from .openvla import split_rollouts as split_rollouts_openvla, compute_au_eu_metrics


# ---------------------------------------------------------------------------
# Hand-crafted metrics
# ---------------------------------------------------------------------------

def compute_hand_crafted_metrics(
        cfg: Config,
        policy_records: list[dict],
        exec_horizon: int,
) -> pd.DataFrame:
    '''
    Compute hand-crafted uncertainty / motion metrics for UniVLA rollouts.

    Mirrors the openvla ``compute_hand_crafted_metrics`` interface:
    token-level probability and entropy aggregates (max / avg), plus
    running-mean variants.

    Parameters
    ----------
    cfg : Config
    policy_records : list of dicts
        One dict per inference call within an episode.
    exec_horizon : int
        Number of steps actually executed from each predicted chunk.

    Returns
    -------
    pd.DataFrame  with one row per inference step.
    '''
    metrics_raw: dict[str, list] = {}

    # Collect per-step token_prob and token_entropy arrays
    token_prob_list: list[np.ndarray] = []
    token_entropy_list: list[np.ndarray] = []

    for record in policy_records:
        # token_prob: chosen-token probability per token  (N_tok,)
        if "probs" in record:
            probs = np.asarray(record["probs"], dtype=np.float32)  # (N_tok,)
            token_prob_list.append(probs)
        else:
            token_prob_list.append(None)

        # token_entropy: entropy approximated from top-K probs  (N_tok,)
        if "top_k_probs" in record:
            top_k = np.asarray(record["top_k_probs"], dtype=np.float32)  # (N_tok, K)
            # Normalise so top-K sums to 1 per token, then compute entropy
            # top_k_norm = top_k / (top_k.sum(axis=1, keepdims=True) + 1e-9)
            entropy_per_tok = -(top_k * np.log(top_k + 1e-9)).sum(axis=1)  # (N_tok,)
            token_entropy_list.append(entropy_per_tok)
        else:
            token_entropy_list.append(None)
    
    max_len = max(a.shape[0] for a in token_prob_list)
    padded = [np.pad(a, (0, max_len - len(a)), mode='edge') for a in token_prob_list]
    token_prob_list = np.stack(padded)


    max_len = max(a.shape[0] for a in token_entropy_list)
    padded = [np.pad(a, (0, max_len - len(a)), mode='edge') for a in token_entropy_list]
    token_entropy_list = np.stack(padded)
    # ---- Token-probability metrics (same as openvla) ----------------------
    has_prob = all(p is not None for p in token_prob_list)
    has_entropy = all(e is not None for e in token_entropy_list)

    if has_prob and has_entropy:
        max_token_prob = token_prob_list.max(axis=-1) # (n_step, )
        avg_token_prob = token_prob_list.mean(axis=-1) # (n_step, )
        max_token_entropy = token_entropy_list.max(axis=-1) # (n_step, )
        avg_token_entropy = token_entropy_list.mean(axis=-1) # (n_step, )
        metrics_raw.update({
            "max_token_prob": max_token_prob,
            "avg_token_prob": avg_token_prob,
            "max_token_entropy": max_token_entropy,
            "avg_token_entropy": avg_token_entropy,
        })

    # ---- Build DataFrame; add running-mean variants (same as openvla) -----
    metrics = {}
    for k, v in metrics_raw.items():
        arr = np.asarray(v)
        metrics[k] = arr
        metrics[f"{k}_rmean"] = np.cumsum(arr) / (np.arange(len(arr)) + 1)

    return pd.DataFrame(metrics)


# ---------------------------------------------------------------------------
# Rollout loading
# ---------------------------------------------------------------------------

def load_rollouts_from_root(load_root: Path, cfg: Config) -> list[Rollout]:
    env_records_folder  = load_root / "env_records"
    policy_records_folder = load_root / "policy_records"

    assert env_records_folder.exists(),   f"Path {env_records_folder} does not exist"
    assert policy_records_folder.exists(), f"Path {policy_records_folder} does not exist"

    env_record_paths    = natsort.natsorted(glob.glob(str(env_records_folder / "*.pkl")))
    policy_record_paths = natsort.natsorted(glob.glob(str(policy_records_folder / "*meta.pkl")))

    assert len(env_record_paths) > 0,    f"No env records found in {env_records_folder}"
    assert len(policy_record_paths) > 0, f"No policy records found in {policy_records_folder}"

    all_rollouts = []
    policy_step = 0

    for env_record_path in tqdm(env_record_paths, desc="Loading UniVLA rollouts"):
        env_record = pickle.load(open(env_record_path, "rb"))
        mp4_path   = env_record_path.replace(".pkl", ".mp4")

        model_infer_times = env_record["model_infer_times"]
        policy_records = []
        for _ in range(model_infer_times):
            policy_records.append(
                pickle.load(open(policy_record_paths[policy_step], "rb"))
            )
            policy_step += 1

        # -------------------------------------------------------------------
        # Extract hidden states, action vectors, probs, and top-k probs
        # -------------------------------------------------------------------
        hidden_states_list = []
        action_vectors_list = []
        probs_list = []
        top_k_probs_list = []

        for policy_record in policy_records:
            # feat_name defaults to "hidden_states" → (N_tok, 4096)
            hidden_state = policy_record[cfg.dataset.feat_name]  # np or tensor

            # Convert to float32 tensor if necessary (bfloat16 safeguard)
            if isinstance(hidden_state, np.ndarray):
                hidden_state = torch.from_numpy(hidden_state.astype(np.float32))
            else:
                hidden_state = hidden_state.float()             # tensor path

            # Aggregate over the token dimension → (hidden_dim,)
            hidden_state = process_tensor_idx_rel(hidden_state, cfg.dataset.token_idx_rel)

            hidden_states_list.append(hidden_state)

            pred_horizon = policy_record["actions"].shape[0]
            dim_action   = policy_record["actions"].shape[1]
            action = policy_record["actions"].reshape(-1).astype(np.float32)
            action_vectors_list.append(action)

            # Collect per-step token probabilities  (N_tok,) and top-k probs (N_tok, K)
            if "probs" in policy_record:
                probs_list.append(np.asarray(policy_record["probs"], dtype=np.float32))
            if "top_k_probs" in policy_record:
                top_k_probs_list.append(np.asarray(policy_record["top_k_probs"], dtype=np.float32))

        hidden_states = torch.stack(hidden_states_list, dim=0)   # (n_steps, hidden_dim)
        action_vectors = torch.from_numpy(
            np.stack(action_vectors_list, axis=0)
        )                                                          # (n_steps, pred_horizon*action_dim)

        cfg.dataset.dim_features = hidden_states.shape[-1]
        cfg.dataset.dim_action   = dim_action
        cfg.dataset.pred_horizon = pred_horizon
        cfg.dataset.exec_horizon = env_record['replan_steps']

        # -------------------------------------------------------------------
        # Pad and stack probs / top_k_probs to uniform token length
        # probs_stacked  : (n_steps, max_tokens)
        # top_k_stacked  : (n_steps, max_tokens, K)
        # -------------------------------------------------------------------
        probs_tensor    = None
        top_k_tensor    = None
        au_eu_metrics   = None

        if probs_list:
            max_tokens = max(p.shape[0] for p in probs_list)
            padded_probs = []
            for p in probs_list:
                pad = max_tokens - p.shape[0]
                padded_probs.append(np.concatenate([p, np.zeros(pad)]) if pad > 0 else p)
            probs_stacked = np.stack(padded_probs, axis=0)          # (n_steps, max_tokens)
            probs_tensor  = torch.from_numpy(probs_stacked)         # (n_steps, max_tokens)

        if top_k_probs_list:
            max_tokens = max(t.shape[0] for t in top_k_probs_list)
            K          = top_k_probs_list[0].shape[1]
            padded_top_k = []
            for t in top_k_probs_list:
                pad = max_tokens - t.shape[0]
                padded_top_k.append(
                    np.concatenate([t, np.zeros((pad, K))], axis=0) if pad > 0 else t
                )
            top_k_stacked = np.stack(padded_top_k, axis=0)          # (n_steps, max_tokens, K)
            top_k_tensor  = torch.from_numpy(top_k_stacked)         # (n_steps, max_tokens, K)

            # Compute AU / EU metrics (same framework as openvla)
            if probs_tensor is not None:
                token_entropy = -(top_k_stacked * np.log(top_k_stacked + 1e-9)).sum(axis=-1)  # (n_steps, max_tokens)
                au_eu_metrics = compute_au_eu_metrics(
                    token_prob=probs_stacked,
                    token_entropy=token_entropy,
                    top_10_probs=top_k_stacked,
                )  # (n_steps, max_tokens, 4) or {}

        # -------------------------------------------------------------------
        # Optional hand-crafted metrics
        # -------------------------------------------------------------------
        hand_crafted_metrics = None
        if cfg.train.log_precomputed or cfg.train.log_precomputed_only:
            hand_crafted_metrics = compute_hand_crafted_metrics(
                cfg=cfg,
                policy_records=policy_records,
                exec_horizon=env_record['replan_steps'],
            )
            if cfg.train.log_precomputed_only:
                hidden_states  = torch.zeros((hidden_states.shape[0], 1))
                action_vectors = None

        rollout = Rollout(
            hidden_states=hidden_states,
            probs=probs_tensor,
            top_10_probs=top_k_tensor,
            probs_features=torch.tensor(au_eu_metrics, dtype=torch.float32) if isinstance(au_eu_metrics, np.ndarray) else None,
            task_suite_name=env_record["task_suite_name"],
            task_id=env_record["task_id"],
            task_description=env_record["task_description"],
            episode_idx=env_record["episode_idx"],
            episode_success=env_record["episode_success"],
            mp4_path=mp4_path,
            logs=hand_crafted_metrics,
            exec_horizon=env_record['replan_steps'],
            action_vectors=action_vectors,
        )
        all_rollouts.append(rollout)

    all_rollouts = set_task_min_step(all_rollouts)
    return all_rollouts


def load_rollouts(cfg: Config) -> list[Rollout]:
    load_root = Path(cfg.dataset.data_path)
    all_rollouts = load_rollouts_from_root(load_root, cfg)

    if cfg.dataset.data_path_unseen is not None:
        seen_rollouts  = all_rollouts
        seen_task_ids  = set(r.task_id for r in seen_rollouts)
        n_seen_tasks   = len(seen_task_ids)
        print(f"Seen tasks: {seen_task_ids}")
        print(f"Number of seen tasks: {n_seen_tasks}")

        unseen_root    = Path(cfg.dataset.data_path_unseen)
        unseen_rollouts = load_rollouts_from_root(unseen_root, cfg)
        for r in unseen_rollouts:
            r.task_id += n_seen_tasks

        unseen_task_ids = set(r.task_id for r in unseen_rollouts)
        n_unseen_tasks  = len(unseen_task_ids)
        print(f"Unseen tasks: {unseen_task_ids}")
        print(f"Number of unseen tasks: {n_unseen_tasks}")

        cfg.dataset.unseen_task_ratio = n_unseen_tasks / (n_seen_tasks + n_unseen_tasks)
        print(f"Overwrite unseen_task_ratio: {cfg.dataset.unseen_task_ratio}")

        all_rollouts = seen_rollouts + unseen_rollouts

    return all_rollouts


def split_rollouts(cfg: Config, all_rollouts: list[Rollout]) -> dict[str, list[Rollout]]:
    if cfg.dataset.data_path_unseen is None:
        return split_rollouts_openvla(cfg, all_rollouts)

    task_ids   = sorted(set(r.task_id for r in all_rollouts))
    n_unseen   = round(cfg.dataset.unseen_task_ratio * len(task_ids))
    n_seen     = len(task_ids) - n_unseen
    seen_task_ids   = task_ids[:n_seen]
    unseen_task_ids = task_ids[n_seen:]

    return split_rollouts_by_seen_unseen(cfg, all_rollouts, seen_task_ids, unseen_task_ids)
